import { createFileRoute } from "@tanstack/react-router";
import { Edit3, Eye, FileText, Plus, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { AdminModuleShell } from "@/components/admin-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { API_BASE_URL, adminAction, adminList } from "@/lib/vehicle-platform";
export const Route = createFileRoute("/admin/content")({ head: () => ({ meta: [{ title: "Content | AWA Admin" }] }), component: ContentAdminPage });
type Article = { id?: number; title: string; slug?: string; excerpt?: string; status: string; updated_at?: string; published_at?: string };
const demo: Article[] = [{ title: "How to import a vehicle", status: "Published", updated_at: "Sep 16, 2026" }, { title: "Understanding vehicle shipping", status: "Draft", updated_at: "Sep 14, 2026" }];
function ContentAdminPage() { const [items, setItems] = useState(demo); const [live, setLive] = useState(false); const [loading, setLoading] = useState(Boolean(API_BASE_URL)); const load = () => { if (!API_BASE_URL) { setLoading(false); return; } setLoading(true); adminList<Article>("articles").then((r) => { setItems(r.data); setLive(true); }).catch(() => setLive(false)).finally(() => setLoading(false)); }; useEffect(load, []); async function toggle(item: Article) { if (!item.id) return; const action = item.status === "Published" ? "unpublish" : "publish"; try { await adminAction("articles", item.id, action); setItems((all) => all.map((x) => x.id === item.id ? { ...x, status: action === "publish" ? "Published" : "Draft" } : x)); } catch (e) { alert(e instanceof Error ? e.message : "Publishing failed"); } } return <AdminModuleShell title="Content studio" eyebrow="Publishing"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Create, review, publish, and maintain news and automotive guides.</p><p className="mt-1 text-xs font-semibold text-slate-400">{loading ? "Syncing…" : live ? "Live API data" : "Demo data"}</p></div><div className="flex gap-2"><Button variant="outline" onClick={load}><RefreshCw /> Refresh</Button><Button variant="automotive"><Plus /> New article</Button></div></div><div className="grid gap-4 sm:grid-cols-2">{items.map((item, i) => <article key={item.id ?? item.title ?? i} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><FileText className="h-5 w-5" /></div><Badge variant={item.status === "Published" ? "default" : "secondary"}>{item.status}</Badge></div><h2 className="mt-5 text-xl font-extrabold uppercase">{item.title}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-500">{item.excerpt || "Article content managed through the PHP API."}</p><p className="mt-2 text-xs text-slate-500">Last updated {item.updated_at || "—"}</p><div className="mt-5 flex gap-2"><Button variant="outline" className="flex-1"><Edit3 /> Edit</Button><Button variant="outline" size="icon"><Eye /></Button>{item.id && <Button onClick={() => toggle(item)} variant="outline">{item.status === "Published" ? "Unpublish" : "Publish"}</Button>}</div></article>)}</div>{!live && <div className="mt-6 rounded-2xl border border-dashed border-primary/30 bg-primary/[.04] p-5 text-sm text-slate-600"><strong className="block text-slate-900">Demo data mode</strong>News and article publishing buttons use the live API after deployment credentials are configured.</div>}</AdminModuleShell>; }
