import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Car, CheckCircle2, Globe2, Headphones, PackageSearch, Search, ShieldCheck, Wrench } from "lucide-react";
import { useState, type FormEvent } from "react";
import { motion } from "motion/react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import hero from "@/assets/awa-hero.jpg";
import carsCategory from "@/assets/awa-cars-category.jpg";
import partsCategory from "@/assets/awa-parts-category.jpg";
import showroom from "@/assets/awa-showroom.jpg";
import globalImage from "@/assets/awa-global.jpg";
import { partCategories, parts, vehicles } from "@/lib/inventory";
import { ContactStrip, whatsappUrl } from "./site-shell";
import { PartsGrid, SectionHeading, VehicleGrid } from "./marketplace";

const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.16},transition:{duration:.55}};

export function HomePage(){return <>
 <Hero/>
 <motion.section {...reveal} className="section-pad bg-background"><div className="container-shell"><SectionHeading eyebrow="Browse by category" title="What Are You Looking For?"/><div className="grid gap-5 lg:grid-cols-2"><Category image={carsCategory} title="Cars" copy="Explore quality vehicles for personal, business and commercial needs." to="/cars" label="Explore Cars"/><Category image={partsCategory} title="Spare Parts" copy="Find automotive spare parts for different vehicle makes and models." to="/spare-parts" label="Explore Spare Parts"/></div></div></motion.section>
 <motion.section {...reveal} className="section-pad bg-secondary"><div className="container-shell"><SectionHeading eyebrow="Vehicle inventory" title="Featured Vehicles" copy="Explore some of the vehicles available through AWA AUTO MALL. Inventory shown is representative and subject to confirmation."/><VehicleGrid items={vehicles}/><div className="mt-10 text-center"><Button asChild size="lg"><Link to="/cars">View All Vehicles<ArrowRight/></Link></Button></div></div></motion.section>
 <motion.section {...reveal} className="section-pad bg-background"><div className="container-shell"><SectionHeading eyebrow="Parts supply" title="Automotive Spare Parts" copy="Quality automotive parts sourced for customers and businesses worldwide."/><div className="mb-10 flex gap-2 overflow-x-auto pb-2">{partCategories.map(x=><span key={x} className="shrink-0 border border-border bg-secondary px-4 py-3 text-xs font-bold uppercase">{x}</span>)}</div><PartsGrid items={parts}/><div className="mt-10"><Button asChild variant="outline" size="lg"><Link to="/spare-parts">Browse Spare Parts<ArrowRight/></Link></Button></div></div></motion.section>
 <GlobalSection/>
 <WhySection/>
 <ProcessSection/>
 <motion.section {...reveal} className="section-pad bg-background"><div className="container-shell grid items-center gap-10 lg:grid-cols-2"><img src={showroom} alt="Modern vehicle sourcing and inspection environment in Guangzhou" width={1600} height={1000} loading="lazy" className="min-h-[420px] w-full object-cover"/><div><SectionHeading eyebrow="About AWA" title="Driven By Quality. Built For The Global Market." copy="AWA AUTO MALL specializes in the sale of cars and automotive spare parts globally. Based in Guangzhou, China, we provide customers with access to vehicles and automotive products while focusing on quality, professional service and dependable communication."/><Button asChild size="lg"><Link to="/about">Learn More About Us<ArrowRight/></Link></Button></div></div></motion.section>
 <InquirySection/>
 <section className="section-pad bg-secondary"><div className="container-shell"><SectionHeading eyebrow="Contact" title="Let’s Talk Automotive" copy="Connect with AWA AUTO MALL in Guangzhou for a vehicle or spare-parts inquiry."/><ContactStrip/></div></section>
 </>}

function Hero(){const navigate=useNavigate();const [kind,setKind]=useState<"cars"|"spare-parts">("cars"); return <section className="relative min-h-[calc(100svh-5rem)] overflow-hidden bg-navy text-primary-foreground"><img src={hero} alt="Premium SUV in a modern city showroom" width={1920} height={1080} fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-[62%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-surface-dark via-surface-dark/70 to-transparent"/><div className="container-shell relative flex min-h-[calc(100svh-5rem)] items-center py-16"><div className="max-w-3xl"><motion.p initial={{opacity:0}} animate={{opacity:1}} className="mb-5 flex items-center gap-3 text-sm font-bold uppercase"><span className="h-0.5 w-10 bg-destructive"/>Guangzhou · Global Automotive Sourcing</motion.p><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}} className="text-5xl font-extrabold uppercase leading-[.9] sm:text-7xl lg:text-8xl">Your Trusted Source for <span className="text-primary">Cars</span> & <span className="text-destructive">Spare Parts</span></motion.h1><p className="mt-6 max-w-xl text-base leading-7 text-primary-foreground/75 sm:text-lg">Quality vehicles and automotive spare parts, sourced in China and supplied globally.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/cars">Browse Cars<ArrowRight/></Link></Button><Button asChild variant="inverse" size="lg"><Link to="/spare-parts">Shop Spare Parts</Link></Button></div><form onSubmit={(e)=>{e.preventDefault();navigate({to:kind==="cars"?"/cars":"/spare-parts"})}} className="mt-10 grid max-w-2xl gap-2 border border-primary-foreground/20 bg-surface-dark/80 p-3 backdrop-blur sm:grid-cols-[1fr_auto_auto]"><span className="self-center px-2 text-sm text-primary-foreground/60">What are you looking for?</span><div className="flex bg-primary-foreground/10 p-1"><button type="button" onClick={()=>setKind("cars")} className={`px-4 py-2 text-xs font-bold uppercase ${kind==="cars"?"bg-primary text-primary-foreground":""}`}>Cars</button><button type="button" onClick={()=>setKind("spare-parts")} className={`px-4 py-2 text-xs font-bold uppercase ${kind==="spare-parts"?"bg-primary text-primary-foreground":""}`}>Spare Parts</button></div><Button type="submit" variant="automotive" size="lg"><Search/>Search</Button></form></div></div></section>}

function Category({image,title,copy,to,label}:{image:string;title:string;copy:string;to:"/cars"|"/spare-parts";label:string}){return <article className="group relative min-h-[430px] overflow-hidden bg-navy"><img src={image} alt={`${title} available through AWA AUTO MALL`} width={1600} height={1000} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-surface-dark via-surface-dark/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-primary-foreground sm:p-9"><h3 className="text-4xl font-extrabold uppercase">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-primary-foreground/70">{copy}</p><Button asChild variant="inverse" className="mt-6"><Link to={to}>{label}<ArrowRight/></Link></Button></div></article>}

function GlobalSection(){return <motion.section {...reveal} className="relative min-h-[620px] overflow-hidden bg-navy"><img src={globalImage} alt="Vehicles prepared for international automotive logistics" width={1600} height={1000} loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-surface-dark via-surface-dark/80 to-transparent"/><div className="container-shell relative flex min-h-[620px] items-center"><div className="max-w-2xl"><Globe2 className="mb-6 h-10 w-10 text-destructive"/><SectionHeading eyebrow="Global automotive sourcing" title="Automotive Solutions Without Borders" copy="From our base in Guangzhou, China, AWA AUTO MALL connects customers with vehicles and automotive spare parts for markets around the world." inverse/><div className="flex items-center gap-4 border-l-2 border-destructive pl-5 text-sm text-primary-foreground/70"><strong className="text-primary-foreground">Guangzhou, China</strong><ArrowRight/>International markets</div></div></div></motion.section>}

const reasons=[[ShieldCheck,"Quality Selection","Vehicles and products are sourced around clearly defined customer requirements."],[Globe2,"Global Sourcing","Internationally focused support from our base in Guangzhou, China."],[Wrench,"Automotive Expertise","Practical knowledge across vehicles and automotive spare parts."],[CheckCircle2,"Reliable Service","Clear updates and dependable communication throughout your inquiry."],[Car,"Cars & Spare Parts","One trusted contact for vehicle and automotive product requirements."],[Headphones,"Customer-Focused Support","Professional assistance shaped around what you need."]];
export function WhySection(){return <section className="section-pad bg-background"><div className="container-shell"><SectionHeading eyebrow="Why AWA" title="Why Choose AWA AUTO MALL?"/><div className="grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-3">{reasons.map(([Icon,title,copy],i)=><article key={String(title)} className="border-b border-r border-border p-7"><span className="text-sm font-bold text-destructive">0{i+1}</span><Icon className="mt-8 h-8 w-8 text-primary"/><h3 className="mt-5 text-2xl font-bold uppercase">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{String(copy)}</p></article>)}</div></div></section>}

const steps=[["Tell Us What You Need","Send us the vehicle or spare-part requirements."],["We Source It","Our team searches for the appropriate vehicle or automotive product."],["Review & Confirm","Receive product information, images and available details."],["Complete Your Purchase","Proceed with the agreed purchasing and delivery arrangements."]];
function ProcessSection(){return <section className="section-pad bg-secondary"><div className="container-shell"><SectionHeading eyebrow="Simple process" title="How It Works"/><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">{steps.map(([title,copy],i)=><article key={title} className="border-t-2 border-primary pt-6"><span className="text-5xl font-extrabold text-border">0{i+1}</span><h3 className="mt-5 text-xl font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section>}

export function InquirySection(){const [error,setError]=useState(""); function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get("name")||"").trim();const phone=String(fd.get("phone")||"").trim();const details=String(fd.get("details")||"").trim();if(!name||!phone||!details){setError("Please complete your name, phone number, and vehicle or part details.");return} const msg=`AWA AUTO MALL inquiry\nName: ${name}\nPhone: ${phone}\nEmail: ${String(fd.get("email")||"")}\nLooking for: ${String(fd.get("type")||"")}\nDetails: ${details}\nMake/Model: ${String(fd.get("model")||"")}\nQuantity: ${String(fd.get("quantity")||"")}\nMessage: ${String(fd.get("message")||"")}`;window.open(whatsappUrl(msg),"_blank","noopener,noreferrer")}
return <section className="section-pad bg-navy text-primary-foreground" id="inquiry"><div className="container-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><PackageSearch className="mb-7 h-10 w-10 text-destructive"/><SectionHeading eyebrow="Direct inquiry" title="Looking For A Specific Vehicle Or Part?" copy="Tell us what you need and our team will help you with the available options." inverse/><a href={whatsappUrl()} className="inline-flex items-center gap-2 font-bold"><span className="grid h-10 w-10 place-items-center rounded-full bg-primary"><Headphones className="h-5 w-5"/></span>Chat With Us On WhatsApp</a></div><form onSubmit={submit} className="grid gap-4 bg-background p-6 text-foreground sm:grid-cols-2 sm:p-8"><Field label="Full Name *"><Input name="name" maxLength={100} required/></Field><Field label="Phone Number *"><Input name="phone" type="tel" maxLength={30} required/></Field><Field label="Email"><Input name="email" type="email" maxLength={255}/></Field><Field label="What Are You Looking For?"><select name="type" className="h-10 w-full border border-input bg-background px-3 text-sm"><option>Vehicle</option><option>Spare Part</option></select></Field><Field label="Vehicle / Part Details *" wide><Input name="details" maxLength={200} required/></Field><Field label="Preferred Make or Model"><Input name="model" maxLength={100}/></Field><Field label="Quantity"><Input name="quantity" type="number" min="1" max="9999"/></Field><Field label="Message" wide><Textarea name="message" maxLength={1000} className="min-h-28"/></Field>{error&&<p role="alert" className="text-sm font-semibold text-destructive sm:col-span-2">{error}</p>}<Button type="submit" variant="automotive" size="lg" className="sm:col-span-2">Send Inquiry<ArrowRight/></Button></form></div></section>}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"sm:col-span-2":""}><span className="mb-2 block text-xs font-bold uppercase text-muted-foreground">{label}</span>{children}</label>}