/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SparePartsRouteImport } from './routes/spare-parts'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WhyAwaRouteImport } from './routes/why-awa'
import { Route as CarsSlugRouteImport } from './routes/cars.$slug'
import { Route as CarsBrandsRouteImport } from './routes/cars/brands'
import { Route as CarsModelsRouteImport } from './routes/cars/models'
import { Route as CarsTypesRouteImport } from './routes/cars/types'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as SparePartsSlugRouteImport } from './routes/spare-parts.$slug'
import { Route as CarsBrandsBrandRouteImport } from './routes/cars/brands/$brand'
import { Route as CarsModelsModelRouteImport } from './routes/cars/models/$model'
import { Route as CarsTypesTypeRouteImport } from './routes/cars/types/$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsRoute = SparePartsRouteImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyAwaRoute = WhyAwaRouteImport.update({
  id: '/why-awa',
  path: '/why-awa',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarsRoute,
} as any)
const CarsBrandsRoute = CarsBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => CarsRoute,
} as any)
const CarsModelsRoute = CarsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => CarsRoute,
} as any)
const CarsTypesRoute = CarsTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => CarsRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsSlugRoute = SparePartsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SparePartsRoute,
} as any)
const CarsBrandsBrandRoute = CarsBrandsBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => CarsBrandsRoute,
} as any)
const CarsModelsModelRoute = CarsModelsModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => CarsModelsRoute,
} as any)
const CarsTypesTypeRoute = CarsTypesTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => CarsTypesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/shipping': typeof ShippingRoute
  '/spare-parts': typeof SparePartsRouteWithChildren
  '/track-order': typeof TrackOrderRoute
  '/why-awa': typeof WhyAwaRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/brands': typeof CarsBrandsRouteWithChildren
  '/cars/models': typeof CarsModelsRouteWithChildren
  '/cars/types': typeof CarsTypesRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/spare-parts/$slug': typeof SparePartsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/cars/brands/$brand': typeof CarsBrandsBrandRoute
  '/cars/models/$model': typeof CarsModelsModelRoute
  '/cars/types/$type': typeof CarsTypesTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/shipping': typeof ShippingRoute
  '/spare-parts': typeof SparePartsRouteWithChildren
  '/track-order': typeof TrackOrderRoute
  '/why-awa': typeof WhyAwaRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/brands': typeof CarsBrandsRouteWithChildren
  '/cars/models': typeof CarsModelsRouteWithChildren
  '/cars/types': typeof CarsTypesRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/spare-parts/$slug': typeof SparePartsSlugRoute
  '/news': typeof NewsIndexRoute
  '/cars/brands/$brand': typeof CarsBrandsBrandRoute
  '/cars/models/$model': typeof CarsModelsModelRoute
  '/cars/types/$type': typeof CarsTypesTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/shipping': typeof ShippingRoute
  '/spare-parts': typeof SparePartsRouteWithChildren
  '/track-order': typeof TrackOrderRoute
  '/why-awa': typeof WhyAwaRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/brands': typeof CarsBrandsRouteWithChildren
  '/cars/models': typeof CarsModelsRouteWithChildren
  '/cars/types': typeof CarsTypesRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/spare-parts/$slug': typeof SparePartsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/cars/brands/$brand': typeof CarsBrandsBrandRoute
  '/cars/models/$model': typeof CarsModelsModelRoute
  '/cars/types/$type': typeof CarsTypesTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cars'
    | '/compare'
    | '/contact'
    | '/shipping'
    | '/spare-parts'
    | '/track-order'
    | '/why-awa'
    | '/cars/$slug'
    | '/cars/brands'
    | '/cars/models'
    | '/cars/types'
    | '/news/$slug'
    | '/spare-parts/$slug'
    | '/news/'
    | '/cars/brands/$brand'
    | '/cars/models/$model'
    | '/cars/types/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cars'
    | '/compare'
    | '/contact'
    | '/shipping'
    | '/spare-parts'
    | '/track-order'
    | '/why-awa'
    | '/cars/$slug'
    | '/cars/brands'
    | '/cars/models'
    | '/cars/types'
    | '/news/$slug'
    | '/spare-parts/$slug'
    | '/news'
    | '/cars/brands/$brand'
    | '/cars/models/$model'
    | '/cars/types/$type'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cars'
    | '/compare'
    | '/contact'
    | '/shipping'
    | '/spare-parts'
    | '/track-order'
    | '/why-awa'
    | '/cars/$slug'
    | '/cars/brands'
    | '/cars/models'
    | '/cars/types'
    | '/news/$slug'
    | '/spare-parts/$slug'
    | '/news/'
    | '/cars/brands/$brand'
    | '/cars/models/$model'
    | '/cars/types/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarsRoute: typeof CarsRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ShippingRoute: typeof ShippingRoute
  SparePartsRoute: typeof SparePartsRouteWithChildren
  TrackOrderRoute: typeof TrackOrderRoute
  WhyAwaRoute: typeof WhyAwaRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-awa': {
      id: '/why-awa'
      path: '/why-awa'
      fullPath: '/why-awa'
      preLoaderRoute: typeof WhyAwaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/brands': {
      id: '/cars/brands'
      path: '/brands'
      fullPath: '/cars/brands'
      preLoaderRoute: typeof CarsBrandsRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/models': {
      id: '/cars/models'
      path: '/models'
      fullPath: '/cars/models'
      preLoaderRoute: typeof CarsModelsRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/types': {
      id: '/cars/types'
      path: '/types'
      fullPath: '/cars/types'
      preLoaderRoute: typeof CarsTypesRouteImport
      parentRoute: typeof CarsRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts/$slug': {
      id: '/spare-parts/$slug'
      path: '/$slug'
      fullPath: '/spare-parts/$slug'
      preLoaderRoute: typeof SparePartsSlugRouteImport
      parentRoute: typeof SparePartsRoute
    }
    '/cars/brands/$brand': {
      id: '/cars/brands/$brand'
      path: '/$brand'
      fullPath: '/cars/brands/$brand'
      preLoaderRoute: typeof CarsBrandsBrandRouteImport
      parentRoute: typeof CarsBrandsRoute
    }
    '/cars/models/$model': {
      id: '/cars/models/$model'
      path: '/$model'
      fullPath: '/cars/models/$model'
      preLoaderRoute: typeof CarsModelsModelRouteImport
      parentRoute: typeof CarsModelsRoute
    }
    '/cars/types/$type': {
      id: '/cars/types/$type'
      path: '/$type'
      fullPath: '/cars/types/$type'
      preLoaderRoute: typeof CarsTypesTypeRouteImport
      parentRoute: typeof CarsTypesRoute
    }
  }
}

interface CarsBrandsRouteChildren {
  CarsBrandsBrandRoute: typeof CarsBrandsBrandRoute
}

const CarsBrandsRouteChildren: CarsBrandsRouteChildren = {
  CarsBrandsBrandRoute: CarsBrandsBrandRoute,
}

const CarsBrandsRouteWithChildren = CarsBrandsRoute._addFileChildren(
  CarsBrandsRouteChildren,
)

interface CarsModelsRouteChildren {
  CarsModelsModelRoute: typeof CarsModelsModelRoute
}

const CarsModelsRouteChildren: CarsModelsRouteChildren = {
  CarsModelsModelRoute: CarsModelsModelRoute,
}

const CarsModelsRouteWithChildren = CarsModelsRoute._addFileChildren(
  CarsModelsRouteChildren,
)

interface CarsTypesRouteChildren {
  CarsTypesTypeRoute: typeof CarsTypesTypeRoute
}

const CarsTypesRouteChildren: CarsTypesRouteChildren = {
  CarsTypesTypeRoute: CarsTypesTypeRoute,
}

const CarsTypesRouteWithChildren = CarsTypesRoute._addFileChildren(
  CarsTypesRouteChildren,
)

interface CarsRouteChildren {
  CarsSlugRoute: typeof CarsSlugRoute
  CarsBrandsRoute: typeof CarsBrandsRouteWithChildren
  CarsModelsRoute: typeof CarsModelsRouteWithChildren
  CarsTypesRoute: typeof CarsTypesRouteWithChildren
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsSlugRoute: CarsSlugRoute,
  CarsBrandsRoute: CarsBrandsRouteWithChildren,
  CarsModelsRoute: CarsModelsRouteWithChildren,
  CarsTypesRoute: CarsTypesRouteWithChildren,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface SparePartsRouteChildren {
  SparePartsSlugRoute: typeof SparePartsSlugRoute
}

const SparePartsRouteChildren: SparePartsRouteChildren = {
  SparePartsSlugRoute: SparePartsSlugRoute,
}

const SparePartsRouteWithChildren = SparePartsRoute._addFileChildren(
  SparePartsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarsRoute: CarsRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ShippingRoute: ShippingRoute,
  SparePartsRoute: SparePartsRouteWithChildren,
  TrackOrderRoute: TrackOrderRoute,
  WhyAwaRoute: WhyAwaRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
