/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as SparePartsRouteImport } from './routes/spare-parts'
import { Route as CarsSlugRouteImport } from './routes/cars.$slug'
import { Route as SparePartsSlugRouteImport } from './routes/spare-parts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsRoute = SparePartsRouteImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarsRoute,
} as any)
const SparePartsSlugRoute = SparePartsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SparePartsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/spare-parts': typeof SparePartsRouteWithChildren
  '/cars/$slug': typeof CarsSlugRoute
  '/spare-parts/$slug': typeof SparePartsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/spare-parts': typeof SparePartsRouteWithChildren
  '/cars/$slug': typeof CarsSlugRoute
  '/spare-parts/$slug': typeof SparePartsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/spare-parts': typeof SparePartsRouteWithChildren
  '/cars/$slug': typeof CarsSlugRoute
  '/spare-parts/$slug': typeof SparePartsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cars' | '/spare-parts' | '/cars/$slug' | '/spare-parts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars' | '/spare-parts' | '/cars/$slug' | '/spare-parts/$slug'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/spare-parts'
    | '/cars/$slug'
    | '/spare-parts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRoute: typeof CarsRouteWithChildren
  SparePartsRoute: typeof SparePartsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof CarsRoute
    }
    '/spare-parts/$slug': {
      id: '/spare-parts/$slug'
      path: '/$slug'
      fullPath: '/spare-parts/$slug'
      preLoaderRoute: typeof SparePartsSlugRouteImport
      parentRoute: typeof SparePartsRoute
    }
  }
}

interface CarsRouteChildren {
  CarsSlugRoute: typeof CarsSlugRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsSlugRoute: CarsSlugRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface SparePartsRouteChildren {
  SparePartsSlugRoute: typeof SparePartsSlugRoute
}

const SparePartsRouteChildren: SparePartsRouteChildren = {
  SparePartsSlugRoute: SparePartsSlugRoute,
}

const SparePartsRouteWithChildren = SparePartsRoute._addFileChildren(
  SparePartsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRoute: CarsRouteWithChildren,
  SparePartsRoute: SparePartsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
